# Generated by Django 3.1.4 on 2020-12-14 06:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.expressions


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Corporation',
            fields=[
                ('corporationID', models.AutoField(db_column='CORPORATION_ID', primary_key=True, serialize=False)),
                ('corpName', models.CharField(db_column='CORPORATION_NAME', max_length=30)),
                ('registrationNo', models.CharField(db_column='REGISTRATION_NO', max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('couponID', models.CharField(db_column='COUPON_ID', max_length=10, primary_key=True, serialize=False)),
                ('discount', models.DecimalField(db_column='DISCOUNT', decimal_places=2, max_digits=2)),
                ('validFrom', models.DateField(db_column='VALID_FROM')),
                ('validTo', models.DateField(db_column='VALID_TO')),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('customerID', models.AutoField(db_column='USER_ID', primary_key=True, serialize=False)),
                ('firstName', models.CharField(db_column='FIRST_NAME', max_length=30)),
                ('lastName', models.CharField(db_column='LAST_NAME', max_length=30)),
                ('emailID', models.CharField(db_column='EMAIL_ID', max_length=100, unique=True)),
                ('phoneNo', models.CharField(db_column='PHONE_ID', max_length=10)),
                ('streetAddr', models.CharField(db_column='STREET_ADDR', max_length=50)),
                ('city', models.CharField(db_column='CITY', max_length=30)),
                ('state', models.CharField(db_column='STATE', max_length=2)),
                ('zipcode', models.CharField(db_column='ZIPCODE', max_length=5)),
                ('customerType', models.CharField(choices=[('I', 'I'), ('C', 'C')], db_column='CUST_TYPE', max_length=1)),
            ],
            options={
                'unique_together': {('emailID', 'phoneNo')},
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('invoiceID', models.AutoField(db_column='INVOICE_ID', primary_key=True, serialize=False)),
                ('firstName', models.CharField(db_column='INVOICE_FIRST_NAME', max_length=50, null=True)),
                ('lastName', models.CharField(db_column='INVOICE_LAST_NAME', max_length=50, null=True)),
                ('invoiceDate', models.DateTimeField(auto_now_add=True, db_column='INVOICE_DATE')),
                ('amount', models.DecimalField(db_column='AMOUNT', decimal_places=2, max_digits=10)),
                ('remainingAmount', models.DecimalField(db_column='REMAIN_AMOUNT', decimal_places=2, max_digits=10, null=True)),
                ('status', models.CharField(choices=[('U', 'U'), ('F', 'F')], db_column='STATUS', default='U', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Office',
            fields=[
                ('ofcID', models.AutoField(db_column='OFFICE_ID', primary_key=True, serialize=False)),
                ('ofcStreetAddr', models.CharField(db_column='STREET_ADDR', max_length=50)),
                ('ofcCity', models.CharField(db_column='CITY', max_length=30)),
                ('ofcState', models.CharField(db_column='STATE', max_length=2)),
                ('ofcZipcode', models.CharField(db_column='ZIPCODE', max_length=5)),
                ('ofcPhoneNo', models.CharField(db_column='PHONE_NO', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='vehicleClass',
            fields=[
                ('typeID', models.AutoField(db_column='TYPE_ID', primary_key=True, serialize=False)),
                ('type', models.CharField(db_column='TYPE', max_length=20)),
                ('rentCharge', models.DecimalField(db_column='R_RATE', decimal_places=2, max_digits=5)),
                ('extraCharge', models.DecimalField(db_column='EXTRA_FEE', decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='corporationCustomer',
            fields=[
                ('customerID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='func.customer')),
                ('employeeID', models.CharField(db_column='EMPLOYEE_ID', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='individualCustomer',
            fields=[
                ('customerID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='func.customer')),
                ('driverLicenceNo', models.CharField(db_column='DRIVER_LICENCE_NO', max_length=10)),
                ('insuranceCompany', models.CharField(db_column='INSURANCE_COMPANY', max_length=30)),
                ('insurancePolicyNo', models.CharField(db_column='INSURANCE_POLICY_NO', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('vehicleID', models.AutoField(db_column='VEHICLE_ID', primary_key=True, serialize=False)),
                ('make', models.CharField(db_column='MAKE', max_length=20)),
                ('model', models.CharField(db_column='MODEL', max_length=20)),
                ('year', models.CharField(db_column='YEAR', max_length=4)),
                ('vin', models.CharField(db_column='VIN', max_length=7)),
                ('licensePlateNo', models.CharField(db_column='LICENSE_PLATE_NO', max_length=6)),
                ('vehiclePhoto', models.ImageField(default='NULL', upload_to='vehicle/')),
                ('locationID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='func.office')),
                ('typeID', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='func.vehicleclass')),
            ],
        ),
        migrations.CreateModel(
            name='userClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_customer', models.BooleanField(db_column='IS_CUSTOMER', default=False)),
                ('userID', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='Class', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='rentalService',
            fields=[
                ('rsID', models.AutoField(db_column='RSID', primary_key=True, serialize=False)),
                ('firstName', models.CharField(blank=True, db_column='FIRST_NAME', max_length=50, null=True)),
                ('lastName', models.CharField(blank=True, db_column='LAST_NAME', max_length=50, null=True)),
                ('pickupDate', models.DateField(db_column='PICKUP_DATE')),
                ('dropoffDate', models.DateField(db_column='DROPOFF_DATE')),
                ('startOdometer', models.DecimalField(blank=True, db_column='START_ODOMETER', decimal_places=2, max_digits=7, null=True)),
                ('endOdometer', models.DecimalField(blank=True, db_column='END_ODOMETER', decimal_places=2, max_digits=7, null=True)),
                ('dailyLimit', models.DecimalField(blank=True, db_column='DAILY_LIMIT', decimal_places=2, max_digits=6, null=True)),
                ('status', models.CharField(choices=[('P', 'P'), ('U', 'U'), ('F', 'F')], default='P', max_length=10, verbose_name='STATUS')),
                ('couponID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='func.coupon')),
                ('customerID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='func.customer')),
                ('dropoffOffice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drop_off', to='func.office')),
                ('invoiceID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='rental_invoice', to='func.invoice')),
                ('pickupOffice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='func.office')),
                ('vehicleID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='func.vehicle')),
            ],
        ),
        migrations.CreateModel(
            name='pendingService',
            fields=[
                ('psID', models.AutoField(db_column='PSID', primary_key=True, serialize=False)),
                ('pickupDate', models.DateField(db_column='PICKUP_DATE')),
                ('couponID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='func.coupon')),
                ('customerID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='func.customer')),
                ('pickupOffice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='func.office')),
                ('vehicleID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='func.vehicle')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('paymentID', models.AutoField(db_column='PAYMENT_ID', primary_key=True, serialize=False)),
                ('payMethod', models.CharField(db_column='PAY_METHOD', max_length=50, null=True)),
                ('cardNum', models.CharField(db_column='CARD_NUM', max_length=16, null=True)),
                ('payAmount', models.DecimalField(db_column='PAY_AMOUNT', decimal_places=2, max_digits=7, null=True)),
                ('payDate', models.DateTimeField(auto_now=True, db_column='PAY_DATE')),
                ('invoiceID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_query_name='pay_invoice', to='func.invoice')),
            ],
        ),
        migrations.CreateModel(
            name='Coupon_Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('couponID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='func.coupon')),
                ('customerID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='func.customer')),
            ],
        ),
        migrations.AddConstraint(
            model_name='coupon',
            constraint=models.CheckConstraint(check=models.Q(validFrom__lt=django.db.models.expressions.F('validTo')), name='from_date_lt_to'),
        ),
        migrations.AddField(
            model_name='corporationcustomer',
            name='corporationID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='func.corporation'),
        ),
    ]
