# Generated by Django 3.1.4 on 2020-12-14 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('func', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Coupon_Customer',
        ),
    ]
