# Generated by Django 3.1.4 on 2020-12-14 06:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('func', '0002_delete_coupon_customer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon_Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('couponID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='func.coupon')),
                ('customerID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='func.customer')),
            ],
        ),
    ]
