# Generated by Django 3.1.4 on 2020-12-14 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('func', '0003_coupon_customer'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Coupon_Customer',
            new_name='Coupon1_Customer1',
        ),
    ]
