# Generated by Django 3.1.4 on 2020-12-14 06:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('func', '0004_auto_20201214_0102'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Coupon1_Customer1',
            new_name='Coupon_Customer',
        ),
    ]
