# Generated by Django 3.1.4 on 2020-12-14 07:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('func', '0005_auto_20201214_0104'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='corporation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='func.corporation'),
        ),
        migrations.AddField(
            model_name='coupon',
            name='is_corp',
            field=models.BooleanField(db_column='IS_COUPON', default=False),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='validFrom',
            field=models.DateField(blank=True, db_column='VALID_FROM', null=True),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='validTo',
            field=models.DateField(blank=True, db_column='VALID_TO', null=True),
        ),
    ]
