# Generated by Django 3.1.4 on 2020-12-16 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('func', '0006_auto_20201214_0221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentalservice',
            name='dropoffDate',
            field=models.DateField(blank=True, db_column='DROPOFF_DATE', null=True),
        ),
    ]
