# Generated by Django 3.1.4 on 2020-12-16 06:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('func', '0007_auto_20201216_0118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentalservice',
            name='dropoffOffice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='drop_off', to='func.office'),
        ),
        migrations.AlterField(
            model_name='rentalservice',
            name='pickupOffice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='func.office'),
        ),
    ]
