# Generated by Django 3.1.4 on 2020-12-16 22:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('func', '0008_auto_20201216_0120'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pendingservice',
            name='couponID',
        ),
        migrations.RemoveField(
            model_name='pendingservice',
            name='customerID',
        ),
        migrations.RemoveField(
            model_name='pendingservice',
            name='pickupOffice',
        ),
        migrations.RemoveField(
            model_name='pendingservice',
            name='vehicleID',
        ),
        migrations.AlterField(
            model_name='corporation',
            name='corporationID',
            field=models.AutoField(db_column='CORPORATION_ID', primary_key=True, serialize=False, verbose_name='Corporation'),
        ),
        migrations.AlterField(
            model_name='corporationcustomer',
            name='corporationID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='func.corporation', verbose_name='Corporation'),
        ),
        migrations.AlterField(
            model_name='corporationcustomer',
            name='customerID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='func.customer', verbose_name='Emial'),
        ),
        migrations.AlterField(
            model_name='corporationcustomer',
            name='employeeID',
            field=models.CharField(db_column='EMPLOYEE_ID', max_length=10, verbose_name='Employee ID'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='couponID',
            field=models.CharField(db_column='COUPON_ID', max_length=10, primary_key=True, serialize=False, verbose_name='Coupon Code'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='city',
            field=models.CharField(db_column='CITY', max_length=30, verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='customerID',
            field=models.AutoField(db_column='USER_ID', primary_key=True, serialize=False, verbose_name='Email Address'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='emailID',
            field=models.CharField(db_column='EMAIL_ID', max_length=100, unique=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phoneNo',
            field=models.CharField(db_column='PHONE_ID', max_length=10, verbose_name='Phone Number'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='state',
            field=models.CharField(db_column='STATE', max_length=2, verbose_name='Zipcode'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='streetAddr',
            field=models.CharField(db_column='STREET_ADDR', max_length=50, verbose_name='Street Address'),
        ),
        migrations.AlterField(
            model_name='individualcustomer',
            name='customerID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='func.customer', verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='individualcustomer',
            name='driverLicenceNo',
            field=models.CharField(db_column='DRIVER_LICENCE_NO', max_length=10, verbose_name='Driver Licence No.'),
        ),
        migrations.AlterField(
            model_name='individualcustomer',
            name='insuranceCompany',
            field=models.CharField(db_column='INSURANCE_COMPANY', max_length=30, verbose_name='Insurance Company'),
        ),
        migrations.AlterField(
            model_name='individualcustomer',
            name='insurancePolicyNo',
            field=models.CharField(db_column='INSURANCE_POLICY_NO', max_length=30, verbose_name='Insurance Policy No.'),
        ),
        migrations.AlterField(
            model_name='office',
            name='ofcCity',
            field=models.CharField(db_column='CITY', max_length=30, verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='office',
            name='ofcID',
            field=models.AutoField(db_column='OFFICE_ID', primary_key=True, serialize=False, verbose_name='OfficeID'),
        ),
        migrations.AlterField(
            model_name='office',
            name='ofcPhoneNo',
            field=models.CharField(db_column='PHONE_NO', max_length=10, verbose_name='Contact Number'),
        ),
        migrations.AlterField(
            model_name='office',
            name='ofcState',
            field=models.CharField(db_column='STATE', max_length=2, verbose_name='State'),
        ),
        migrations.AlterField(
            model_name='office',
            name='ofcStreetAddr',
            field=models.CharField(db_column='STREET_ADDR', max_length=50, verbose_name='Office Location'),
        ),
        migrations.AlterField(
            model_name='office',
            name='ofcZipcode',
            field=models.CharField(db_column='ZIPCODE', max_length=5, verbose_name='Zipcode'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='licensePlateNo',
            field=models.CharField(db_column='LICENSE_PLATE_NO', max_length=6, verbose_name='License Plate Number'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='locationID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='func.office', verbose_name='Office'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='typeID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='func.vehicleclass', verbose_name='Vehicle Class'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='vehiclePhoto',
            field=models.ImageField(default='NULL', upload_to='vehicle/', verbose_name='Sample'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='vin',
            field=models.CharField(db_column='VIN', max_length=7, verbose_name='Vehicle Identification Number'),
        ),
        migrations.AddIndex(
            model_name='rentalservice',
            index=models.Index(fields=['customerID'], name='func_rental_custome_11ce92_idx'),
        ),
        migrations.AddIndex(
            model_name='vehicle',
            index=models.Index(fields=['make', 'model', 'year', 'locationID'], name='func_vehicl_MAKE_316210_idx'),
        ),
        migrations.DeleteModel(
            name='pendingService',
        ),
    ]
