# Generated by Django 3.1.4 on 2020-12-16 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('func', '0009_auto_20201216_1750'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['firstName', 'lastName'], name='func_invoic_INVOICE_c8560c_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['invoiceID'], name='func_paymen_invoice_f36a20_idx'),
        ),
    ]
