# Generated by Django 3.1.4 on 2020-12-17 19:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('func', '0010_auto_20201216_1755'),
    ]

    operations = [
        migrations.AlterField(
            model_name='corporationcustomer',
            name='customerID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='func.customer', verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='customerID',
            field=models.AutoField(db_column='USER_ID', primary_key=True, serialize=False, verbose_name='Customer ID'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payMethod',
            field=models.CharField(choices=[('Credit Card', 'Credit Card'), ('Debit Card', 'Debit Card'), ('Gift Card', 'Gift Card')], db_column='PAY_METHOD', max_length=50, null=True),
        ),
    ]
